openapi: 3.0.1
info:
  version: 1.0.0
  title: Hacker News
  description:
    "This is the Open API documentation for the REST API of our beloved
    application **Hackernews** deployed at
    <https://aswprojectdjango.herokuapp.com//>. <br>All operations are
    executable. Only one operation requires authentication: `deleteTweet`. In
    this case, you must **Authorize** your request by providing the api_key
    vaule you got when you created the tweet."
servers:
  - url: "http://aswprojectdjango.herokuapp.com/api"
  - url: "http://127.0.0.1:8000/api"
paths:
  /{username}:
    get:
      tags:
        - user
      summary: Retrieves a User by its username
      description: Returns a user
      operationId: getUserByUsername
      parameters:
        - name: username
          in: path
          description: username of User to return
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
  /submission:
    post:
      tags:
        - Submission
      summary: Post a submission to Hackernews
      operationId: POST_Submission
      requestBody:
        description: Provide the title, url and text required to create the submission
        content:
          application/json:
            schema:
              required:
                - title
                - url
                - text
              type: object
              properties:
                title:
                  type: string
                  minLength: 4
                  example: 'My name'
                url:
                  type: string
                  minLength: 4
                  example: 'https://editor.swagger.io/#'
                text:
                  type: string
                  minLength: 4
                  example: 'Aquest es un enlla√ß que redirecciona al editor swagger'
            required: true
      responses:
        201:
          description: Submission posted
          content:
            application/json:
              schema:
                $ref: ''
        400:
          description: 'Error: Bad Request'
          content:
            application/json:
              schema:
                $ref: ''
              examples:
                errorExample:
                  $ref: ''
    get:
      tags:
        - Submission
      summary: Retrieves all the submissions
      operationId: GET_Submission
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ''

  /submission/{submissionId}:
    get:
      tags:
      - "submissions"
      summary: Finds a Submission by its ID
      description: Returns a single Submission
      operationId: detailedSubmission
      parameters: 
      - name: submissionId
        in: path
        description: ID of the Submission
        required: true
        schema: 
          type: integer
          format: int64
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Submission'
        404:
          description: 'Error: Not Found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
              examples:
                errorExample:
                  $ref: "#/components/examples/error404submssionid"
  /{username}/submissions:
    get:
      tags:
        - submissions
      summary: Retrieves all submissions by user
      operationId: submissionsByUser
      parameters:
        - name: username
          in: path
          description: username to get submissions
          required: true
          schema:
            type: string
            minLength: 1
            example: "pau"
      responses:
        200:
          description: submissions Retrieved
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SubmissionsByUser"
        404:
          description: "Error: Not Found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResult"
              examples:
                errorExample:
                  $ref: "#/components/examples/error404user"
components:
  schemas:
    User:
      type: object
      properties:
        authUser:
          type: object
          properties:
            username:
              type: string
              example: "user43"
            email:
              type: string
              example: "user43@email.com"
            firstName:
              type: string
              example: "userFirstName"
            lastName:
              type: string
              example: "userLastName"
            staffStatus:
              type: boolean
              example: false
        karma:
          type: integer
          format: int64
          example: 2
        about:
          type: string
          example: "Hello, I'm ..."
        showDead:
          type: boolean
          example: false
        noprocrast:
          type: boolean
          example: true
        maxvisit:
          type: string
          maxLength: 16
          example: 100
        minaway:
          type: string
          maxLength: 16
          example: 14
        delay:
          type: string
          maxLength: 16
          example: 24
        created_at_date:
          type: string
          example: "14/02/2094"
        create_at_time:
          type: string
          example: "08:55 CEST"
    Submission:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 2
        title:
          type: string
          maxLength: 50
          example: "Title"
        url:
          type: string
          maxLength: 50
          example: "https://prova.cat"
        text:
          type: string
          format: int32
        type:
          type: string
          maxLength: 3
          default: "url"
          example: "url"
        author:
          type: integer
          example: "4"
        posted_at_date:
          type: string
          example: "2022-05-05"
        posted_at_time:
          type: string
          example: "07:37:19.801"
        upvotes: 
          type: integer
          format: int64
          example: 2
        unvotes:
          type: integer
          format: int64
          example: 1
    AddTweetResult:
      type: object
      properties:
        new_tweet:
          $ref: "#/components/schemas/Submission"
        api_key:
          type: string
          example: "MjAyMC0wNC0xOCAxMjoyODo0MSBVVEM=\n"
    SubmissionsByUser:
      type: object
    ErrorResult:
      type: object
      properties:
        status:
          type: integer
          enum: [400, 401, 403, 404, 409]
        error:
          type: string
          enum:
            [
              "Bad Request",
              "Unauthorized",
              "Forbidden",
              "Not Found",
              "Conflict",
            ]
        message:
          type: string
  examples:
    error400:
      value:
        status: 400
        error: "Bad Request"
        message: "Content is too long (maximum is 280 characters)"
    error401:
      value:
        status: 401
        error: "Unauthorized"
        message: "You provided no api key (X-API-KEY Header)"
    error403:
      value:
        status: 403
        error: "Forbidden"
        message: "Your api key (X-API-KEY Header) is not valid"
    error404user:
      value:
        status: 404
        error: "Not Found"
        message: "No User with that username"
    error404submssionid:
      value:
        status: 404
        error: "Not Found"
        message: "No Submission with that ID"
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      name: X-API-KEY #Custom headers in rails apps must have the X- prefix
      in: header
